### ISSUE TITLE
MIS report issue

### ISSUE THREAD

**Issue by Ayhamhafez** [OCA/account-financial-reporting#136] opened 2015-11-18 10:46 UTC
MIS reports not installed, stuck while installing

**Comment by laetitia-gangloff** [comment] 2015-11-18 12:30
Which version ? (7.0 or 8.0)
Do you have any error message to provide ?
And maybe some step to reproduce your issue ?

**Comment by Ayhamhafez** [comment] 2015-11-18 17:17
Thanks for fast respond

Today I had updated my Odoo V 8 from Github (pull new update), after that I
tried to install MIS module but it doesn't install and not give any error
just stuck on cancel install mode, before updating Odoo it was installed
fine.

**Comment by sbidoul** [comment] 2016-03-17 09:33
Closing because of no answer.

**Closed as completed by sbidoul** 2016-03-17 09:33 UTC
