### ISSUE TITLE
OCA aged receivable misleading behavior

### ISSUE THREAD

**Issue by RenaudArcheTI** [OCA/account-financial-reporting#707] opened 2020-07-13 15:02 UTC
A customer invoice is created with a bill date 2020-04-30 and the invoice is payed on 2020-06-30 and we are after 2020-06-30. If we generate the aged receivable report from OCA for the date 2020-05-31, the invoice previously mentionned should appear. However, right now, it does not apear because it was payed after the date of the report. If we want an aged receivable report at a given date, it should include the invoices that were not paid at this given date even if the invoice was payed after the given date.

**Comment by pedrobaeza** [comment] 2020-07-13 15:10
No, that doesn't happen. This will involve to check also the reconcile dates and can lead to other inconsistencies. The report doesn't pretend to serve as historical payment state, but aged receivable based on a date, but only for still opened items.

If you want to contribute with this other behavior, PRs are welcome, but for now this is the expected behavior.

**Comment by RenaudArcheTI** [comment] 2020-07-13 15:15
@pedrobaeza thank you for your quick answer.

**Comment by mcassuto** [comment] 2020-07-21 03:06
@pedrobaeza @RenaudArcheTI 
Are you talking about the same module / report ?
I retested module account_financial_report on v11 runbot , the Aged Partner Balance does work as expected:
If an invoice is paid today, If I run the report with date 2 days ago, the invoice is marked as due.
=> this is the expected result for this report.

on v13 runbot,  the Aged Partner Balance does *NOT* work as expected:
If an invoice is paid today, If I run the report with date 2 days ago, the invoice is still marked as due.

@pedrobaeza please reopen this issue.

Regards,
Marc

**Comment by JordiBForgeFlow** [comment] 2020-07-21 04:37
@JoanSForgeFlow can you check? 

@mcassuto can you check here? https://github.com/OCA/account-financial-reporting/pull/660 it's the v12 branch that contains the same refactoring done for v13. Should be the same.

In this v12 branch we did not experience this issue.

**Comment by pedrobaeza** [comment] 2020-07-21 07:29
@JordiBForgeFlow have you changed the way it behaves the report?

**Comment by JoanSForgeFlow** [comment] 2020-07-21 12:52
In v11 and v12, If an invoice is paid today and I run the report with date 2 days ago, the invoice appears. It shows the invoices that were not paid at this given date even. In the refactor of v12 works in the same way. (#660)

In v13 right now doesn't work like that, if an invoice is paid it doesn't appear even if it was paid at a later date.

However, we have a PR for v13 that among other changes, also makes it work in the same way as in v11 and v12.(#682)

**Comment by JordiBForgeFlow** [comment] 2020-07-21 13:26
@RenaudArcheTI if you can review #682 then we can merge it sooner.

**Comment by RenaudArcheTI** [comment] 2020-07-22 13:31
@JordiBForgeFlow Ok, I will review #682 .

**Comment by mcassuto** [comment] 2020-07-22 17:05
Note: I did the review also for this specific issue. However, this PR does contain other changes not specifically tested.

**Comment by RenaudArcheTI** [comment] 2020-07-24 13:53
@JordiBForgeFlow I tested #682 . The aged recievable worked the same way as previously, no change on the behavior. There is also a new statement available, the opened items. I tested it, and it gave an error on generation. Should the behavior on the aged receivable have changed or should I use the opened items statement?

Regards,

Renaud

**Comment by mcassuto** [comment] 2020-09-04 20:33
Hello @JordiBForgeFlow ,

any update on this one ?

Thanks

**Comment by JordiBForgeFlow** [comment] 2020-09-04 20:41
@JoanSForgeFlow can you review again? Maybe we are missing something here?

**Comment by mcassuto** [comment] 2020-09-06 01:54
@JordiBForgeFlow I saw the module has been merged (isn't it suprising since this issue was still opened ?? => another subject).
I tested again on the OCA branch => OK for me.
Thanks Jordi.

@RenaudArcheTI please retest as well !

**Comment by RenaudArcheTI** [comment] 2020-09-08 23:16
@JordiBForgeFlow @mcassuto 
I tested again, works great.

Thanks Jordi and Marc.

**Comment by JordiBForgeFlow** [comment] 2020-09-09 07:00
@mcassuto we merged the module in v13 quite a long time ago. Thanks for testing. Now closing the ticket

**Closed as completed by JordiBForgeFlow** 2020-09-09 07:00 UTC
