### ISSUE TITLE
account_financial_report_webkit does not show proper account names

### ISSUE THREAD

**Issue by FSaunier** [OCA/account-financial-reporting#133] opened 2015-11-09 15:29 UTC
The trial balance or general ledger generated from account_financial report_webkit do not show the proper Account Names for existing and _renamed_ accounts from the Chart of Accounts. It shows instead their original names, which I don't know where it gets those from.

This behaviour only happens for existing accounts that have been renamed. Newly created accounts are displayed fine.

Odoo's original Trial Balance/General Ledger has no such issue, and every account name is displayed properly (both newly created or existing and renamed accounts).

**Comment by luc-demeyer** [comment] 2015-11-09 19:32
Can you check if the problem is not caused because you are running a multilingual chart of accounts ?
If this is the problem cause, than it's fixed by PR https://github.com/OCA/account-financial-reporting/pull/123.

**Comment by FSaunier** [comment] 2015-11-09 19:35
I am running the Belgian Chart of accounts, which is installed in French only.

**Comment by luc-demeyer** [comment] 2015-11-09 19:54
If you are running the “l10n_be” module than you have “translate=True" on the "account.account" object (have a look to the "depends" in the __openerp__py and you'll see why). 
Hence you should install the version coming with PR https://github.com/OCA/account-financial-reporting/pull/123 until this fix fully merged within the OCA branch.
As an alternative you can switch from "l10n_be" to the l10n_be_coa_multilang module which gives the option between multi- or single language Chart of Accounts during module installation time (and a whole set of other advantages but that's outside the scope of this issue).

**Comment by FSaunier** [comment] 2015-11-09 20:18
I installed the version from PR #123, and it fixed it for me. Thank you.

**Comment by pedrobaeza** [comment] 2018-03-09 08:24
The PR is merged and solves this issue, so I close.

**Closed as completed by pedrobaeza** 2018-03-09 08:24 UTC
