### ISSUE TITLE
account_financial_report_webkit initial installation

### ISSUE THREAD

**Issue by BT-ojossen** [OCA/account-financial-reporting#70] opened 2015-04-15 13:19 UTC
If you install this module for the first time, the migration script will not be executed (in the older version this code section was under the method "def init" in account_move_line.py file and then it worked). Could you please explain me if or how it should work? or if the first installation has to be done somehow special? Or does it depend on the version of the odoo server?

Best regards

**Comment by pedrobaeza** [comment] 2018-03-09 08:16
You are not indicating version, it's not a bug itself, and very old. Closing. Sorry.

**Closed as completed by pedrobaeza** 2018-03-09 08:16 UTC
