### ISSUE TITLE
[8.0] mis_builder with values zero show empty value

### ISSUE THREAD

**Issue by ovnicraft** [OCA/account-financial-reporting#215] opened 2016-09-01 04:11 UTC
I define a KPI with bals[111] 
- Results:
  ![captura de pantalla de 2016-08-31 23-03-18](https://cloud.githubusercontent.com/assets/31282/18155129/1b57fce0-6fd0-11e6-9f42-fd4e52414bab.png)
- KPI:
  ![captura de pantalla de 2016-08-31 23-07-31](https://cloud.githubusercontent.com/assets/31282/18155130/1f8abeba-6fd0-11e6-8fb0-90239faedf85.png)

Expected: in lines without values set 0

I am using 8.0

**Comment by sbidoul** [comment] 2016-09-01 07:26
There are empty cells when there are no moves in the period for the selected accounts.
When there are moves and sum(debit-credit) = 0, then a 0 is displayed.

This is by design, to distingish "no moves" situations vs debit=credit.

If you need to display zeros in all cases, you could write your expression as `bals[121] or 0.0`.

I'll close the issue. Of course, feel free to reopen if you want to discuss further.

**Closed as completed by sbidoul** 2016-09-01 07:26 UTC

**Comment by ovnicraft** [comment] 2016-09-01 14:12
@sbidoul totally clear, thanks !
