### ISSUE TITLE
Naming issue on Financial Reports module. 

### ISSUE THREAD

**Issue by feketemihai** [OCA/account-financial-reporting#394] opened 2018-03-10 03:57 UTC
We have a naming issue on account_financial_report, the module already exists in Odoo Apps, done by Vauxoo on version before 7.0:
https://www.odoo.com/apps/modules/7.0/account_financial_report/
That's why the module doesn't appear in apps store.
How can we treat this one?
@mreficent @jbeficent @pedrobaeza @moylop260 @nhomar

**Comment by JordiBForgeFlow** [comment] 2018-03-10 06:38
@nhomar, seems that you have discontinued this module after v6.1. Could you remove from the app store?

**Comment by pedrobaeza** [comment] 2018-03-10 14:37
I think he can't simply remove the module, but ask to the Apps responsibles to change the owner somehow.

**Comment by JordiBForgeFlow** [comment] 2018-03-15 11:17
In any case, @nhomar would you agree? Can we mail to Odoo and put you in copy?

**Comment by hbto** [comment] 2018-03-15 14:57
I @hbto Agree on renaming the module on behalf of @nhomar 
endorse my decision @moylop260 

Regards

**Comment by moylop260** [comment] 2018-03-15 15:03
👍

**Comment by JordiBForgeFlow** [comment] 2018-03-15 15:24
Thank you guys!

**Comment by JordiBForgeFlow** [comment] 2018-03-15 15:25
Let us know when you have done so, and we'll oversee if the issue is resolved in the next days.

**Comment by feketemihai** [comment] 2018-03-15 15:27
@nhomar @hbto @moylop260 Thanks for your quick reaction and decision. Hope you will use the module on newer versions..

**Comment by pedrobaeza** [comment] 2018-03-16 17:12
I think you have to start the request to Apps Manager from your side...

**Comment by nhomar** [comment] 2018-04-21 11:54
sorry for the delay, I will ask for the app manager to be removed.

**Comment by JordiBForgeFlow** [comment] 2018-04-21 11:56
They have already fixed https://www.odoo.com/apps/modules/11.0/account_financial_report/

**Closed as completed by JordiBForgeFlow** 2018-04-21 11:56 UTC
