### ISSUE TITLE
Translation of Account name is not working

### ISSUE THREAD

**Issue by NiyasOdootec** [OCA/account-financial-reporting#318] opened 2017-05-31 09:32 UTC
I tried to print trail balance report in arabic language. But still account names are coming in english

**Comment by pedrobaeza** [comment] 2017-05-31 09:33
Version? Module? Steps to reproduce? Is the translation made? If you put on English your string appears?

**Comment by NiyasOdootec** [comment] 2017-05-31 10:21
I installed "account_financial_report_webkit" in odoo8. I am using multi language such that English and Arabic. Then when i print trail balance or general ledger in Arabic language,  translation of account name is not coming.

**Comment by melroy89** [comment] 2017-10-01 15:05
I actually have the same issue with the Dutch language. I installed the 4 modules which are available for Odoo v10 (OCA).

Installed it in: /var/lib/odoo/.local/share/Odoo/addons/10.0/
I do see the nl_NL.po file located in the il18n directory. Odoo is in Dutch, but these modules are still in English, see:

![translation_issue](https://user-images.githubusercontent.com/628926/31055926-ad8bced4-a6ca-11e7-939d-17b8d0e26d4b.png)


Did I forgot something to set it to Dutch or..?

**Comment by melroy89** [comment] 2017-10-03 15:05
I should maybe ask:
 - How can I help to translate? I guess I need to use Poedit (iso transifex).

Since I have the feeling it's not fully translated (or the translation file is not correctly recognized: nl_NL.po or nl_.po).

@pedrobaeza 
Can somebody generate the latest greatest nl.po files for all add-ons? So we don't miss any translation string (new strings that are added in the past, which is not yet part of the PO file).

**EDIT:** AHA! So it is hosted on Transifix, this is not very clear. Maybe but a link to this?

I found this link myself:
https://www.transifex.com/oca/OCA-account-financial-reporting-10-0/ (zero strings to translate :confused:  )

**Comment by luc-demeyer** [comment] 2017-10-03 16:16
This issue if fixed in https://github.com/OCA/account-financial-reporting/pull/123.
Unfortunately the PR never got merged but you can take the diff of this PR, apply it on your system and it will work.

**Comment by melroy89** [comment] 2017-10-04 12:37
I tried to trigger the people to merge the PR.. Hopefully they will....

**Comment by pedrobaeza** [comment] 2018-03-09 08:06
PR is merged, so I close.

**Closed as completed by pedrobaeza** 2018-03-09 08:06 UTC
