### ISSUE TITLE
Odoo Server Error: request of type 'http' but called with a request of type 'json'

### ISSUE THREAD

**Issue by drmedrme** [OCA/account-financial-reporting#434] opened 2018-06-30 17:45 UTC
I have the below error popping up whenever I double click on a number in debt/credit or inital/ending/cumul balance amounts for the generated reports (trial balance, general ledge, etc.).   I read where you could run a nginx reverse proxy and error would not occur, but that does not seem to help.  Currently using odoo server port 8069.  Version 11 Odoo.  Any help or directions on where to look would be appreciated.  

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 318, in _call_function
    raise werkzeug.exceptions.BadRequest(msg % params)
werkzeug.exceptions.BadRequest: 400 Bad Request: <function Home.web_client at 0x7f5e054836a8>, /web: Function declared as capable of handling request of type 'http' but called with a request of type 'json'
```

**Comment by pedrobaeza** [comment] 2018-10-02 13:11
This seems to be a deployment issue, not a bug itself, so closing.

**Closed as completed by pedrobaeza** 2018-10-02 13:11 UTC
